### ISSUE TITLE
urlparse has been renamed to urllib.parse

### ISSUE THREAD

**Issue by SomethingMax2** [basilfx/python-eetlijst#1]
In eetlijst.py there is an issue when trying to import urlparse. To fix this I had to change it to import urllib.parse as urlparse.

**Comment by basilfx** [comment]
Thanks for reporting. That's because this project targeted Python 2 when I released it.

I spent a few hours to 'modernize' this repository. You can check out https://github.com/basilfx/python-eetlijst/pull/5 for the other changes I made.
