### ISSUE TITLE
in line 618 when checking if the returned object is a number or a string it fails.

### ISSUE THREAD

**Issue by SomethingMax2** [basilfx/python-eetlijst#2]
In line 618 when checking if the returned object is a number or a string it fails. This is because when I get the class name, the variable response is of type bytes and doesn't have .status_code. To fix ithis I added the followaing to the if statement:
`if type(response) != str and type(response) != bytes:`

**Comment by basilfx** [comment]
Thanks for reporting. That's because this project targeted Python 2 when I released it.

I spent a few hours to 'modernize' this repository. You can check out https://github.com/basilfx/python-eetlijst/pull/5 for the other changes I made.
